#!/usr/bin/with-contenv bash

echo "*** terrascan installer ***"
echo "Checking if terraform-docs is installed"

if ! /app/terrascan/terrascan -v COMMAND &> /dev/null; then 
  if [ `uname -m` == "aarch64" ] ; then
    curl -Lo /tmp/terrascan.tar.gz $(https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_arm64.tar.gz")
  else
    curl -Lo /tmp/terrascan.tar.gz $(https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")
  fi

  tar -xzf /tmp/terrascan.tar.gz -C /tmp/
  chmod +x /tmp/terrascan
  mkdir -p /app/terrascan 
  mv /tmp/terrascan /app/terrascan/terrascan
  ln -s /app/terrascan/terrascan /usr/local/bin/terrascan

else
  echo "terrascan already installed, skipping!"
fi