#!/usr/bin/with-contenv bash

echo "*** checkov installer ***"
echo "Checking if checkov is installed"

if ! /app/checkov/bin/checkov -v COMMAND &> /dev/null; then 

  apt update
  apt install -y libffi-dev

  pip3 install --upgrade pip && pip3 install --upgrade setuptools
  pip3 install --user --no-cache-dir --prefer-binary \
    --find-links https://wheels.home-assistant.io/alpine-3.14/amd64/ \
    --find-links https://wheels.home-assistant.io/alpine-3.14/aarch64/ \
    checkov

else
  echo "terraform-docs already installed, skipping!"
fi