#!/usr/bin/with-contenv bash

echo "*** terraform-docs installer ***"
echo "Checking if terraform-docs is installed"

if ! /app/terraform-docs/bin/terraform-docs -v COMMAND &> /dev/null; then 
  if [ `uname -m` == "aarch64" ] ; then
    curl -Lo /tmp/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-arm64.tar.gz
  else
    curl -Lo /tmp/terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
  fi

  tar -xzf /tmp/terraform-docs.tar.gz -C /tmp/
  chmod +x /tmp/terraform-docs
  mkdir -p /app/terraform-docs 
  mv /tmp/terraform-docs /app/terraform-docs/terraform-docs

else
  echo "terraform-docs already installed, skipping!"
fi