#!/usr/bin/with-contenv bash

echo "*** tflint installer ***"
echo "Checking if tflint is installed"

apt update
apt install unzip

if ! /app/tflint/tflint -v COMMAND &> /dev/null; then 
  echo "tflint not installed, installing now..." 
  git clone --depth=1 https://github.com/tfutils/tflint.git /app/tflint
  curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | TFLINT_INSTALL_PATH="/app/tflint" bash

  ln -s /app/tflint/tflint /usr/local/bin/tflint
  chown -R abc:abc /app/tflint
else
  echo "tflint already installed, skipping!"
fi
