#!/usr/bin/with-contenv bash

echo "*** infracost installer ***"
echo "Checking if infracost is installed"

if ! /usr/local/bin/infracost -v COMMAND &> /dev/null; then 
  # Downloads the CLI based on your OS/arch and puts it in /usr/local/bin
  curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
else
  echo "infracost already installed, skipping!"
fi